### ISSUE TITLE
Avoid nesting blocks if possible

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-innovatech#18]
https://github.com/PUP-BSIT/project-innovatech/blob/1681fa1ae3869f0b3c1193c2e98a7f4208f2591f/flavorfusion/src/app/header/header.component.ts#L15-L23

Avoid nesting blocks if possible. Use logical operators instead:
```
  ngOnInit() {
    this.router.events.subscribe(event => {
      if (event instanceof NavigationEnd && !this.router.url.includes('/search')) {
          this.resetSearch();
      }
    });
  }
```

**Comment by ssvillarosa** [comment]
You can also use guard clause in this one.
https://github.com/PUP-BSIT/project-innovatech/blob/1681fa1ae3869f0b3c1193c2e98a7f4208f2591f/flavorfusion/src/app/header/header.component.ts#L25-L32

**Comment by Asebuque-ChrystineNoelle** [comment]
Hello, sir. Thank you for your feedback. I've refactored the header component as per your suggestions, removing nested blocks and implementing guard clause for better readability and efficiency.
