### ISSUE TITLE
More than 80 columns

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-innovatech#19]
Fix the column issues in this file:
project-innovatech\flavorfusion\src\app\carousel\carousel.component.html

**Comment by ssvillarosa** [comment]
You still have to follow our HTML and CSS guidelines. It still applies here. Check other files and follow our guidelines.

**Comment by ssvillarosa** [comment]
Team! This ticket is now on its second week. This is not a blockbuster movie. I still don't receive any response/acknowledgement form your end. Do you need a reminder on how to communicate properly?

**Comment by Malaluan-KylaRica** [comment]
Good day, Sir. We apologize for not acknowledging your message sooner. We will keep this in mind and ensure it does not happen again. Thank you po.
