### ISSUE TITLE
Add a TODO

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-innovatech#20]
I believe this object is hardcoded for testing purpose while back end service is under development.
https://github.com/PUP-BSIT/project-innovatech/blob/1681fa1ae3869f0b3c1193c2e98a7f4208f2591f/flavorfusion/src/app/carousel/carousel.component.ts#L9-L34

If this is still applies, kindly add a TODO in this format. https://docs.google.com/presentation/d/1Mdcq3WcHksBlbCvxi6wx5vajn4v8LGlJRnBIu3x4fvw/edit#slide=id.g2ce365fc06d_0_102

It is also better if you mock a service that will return an observable to be subscribed by this component.

Document your code properly during the development so you'll know which portion of the code are temporary.

**Comment by Asebuque-ChrystineNoelle** [comment]
Hello, sir. I've addressed the concern in the carousel component by adding a TODO comment for future improvements regarding the hardcoded object. Thank you for bringing it to my attention.
