### ISSUE TITLE
Move interfaces to model

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-innovatech#21]
If these interfaces are used or will be used by other components, better move this into a model folder and add export keyword.

https://github.com/PUP-BSIT/project-innovatech/blob/1681fa1ae3869f0b3c1193c2e98a7f4208f2591f/flavorfusion/src/app/community/community.component.ts#L4-L22

**Comment by ssvillarosa** [comment]
This field property seems misplaced:
https://github.com/PUP-BSIT/project-innovatech/blob/1681fa1ae3869f0b3c1193c2e98a7f4208f2591f/flavorfusion/src/app/community/community.component.ts#L87

See guidelines: https://docs.google.com/presentation/d/1Mdcq3WcHksBlbCvxi6wx5vajn4v8LGlJRnBIu3x4fvw/edit#slide=id.g2ce365fc0ac_0_5

**Comment by Malaluan-KylaRica** [comment]
Good day, Sir. I have already fixed the issues you mentioned.  I moved my files from my interfaces inside the ts file into a different folder called model and placed my interfaces file inside there. I also properly placed the field property in my ts file. Thank you for bringing up this suggestion; we appreciate your effort in giving us suggestions on how to improve our code.
